"""Action recorder — capture every keystroke, click, and navigation in
the user's TradingView chart so we can learn how they actually drive
the UI.

Two streams interleave in the same JSONL:

  1. **Mechanical** — JS-side capture-phase listeners on the TV page
     translate every input event into a JSON line. We use
     `page.expose_binding(...)` so the page calls back into Python
     directly; no polling, no missed events.
  2. **Intent** — `add_note(text)` appends a free-form line whenever
     the user (or the UI) says "I'm doing X because Y". Same file,
     same timestamps — so reading back the trace one event at a time
     tells the story.

This is a teaching tool, not a production logger. It assumes one
recording at a time on the user's already-attached Chrome.

Output: `tradingview/recordings/<YYYY-MM-DD>_<HHMMSS>.jsonl`.
"""

from __future__ import annotations

import asyncio
import json
import time
from pathlib import Path
from typing import Any

from playwright.async_api import Page, async_playwright

from .lib import audit


# JS injected into every TV page (and re-injected on navigation via
# `page.add_init_script`) so capture starts before TV's own handlers.
# Calls window.__1run_recorder(eventJson) which is bound to Python.
#
# Wrapped as an IIFE — `add_init_script` evaluates the source on
# document creation but never CALLS a bare function expression.
# `evaluate(...)` is more forgiving (it auto-invokes function
# expressions), but using one form for both is simpler.
_RECORDER_JS = r"""
(() => {
  if (window.__1run_recorder_installed) return;
  window.__1run_recorder_installed = true;

  const send = (obj) => {
    try { window.__1run_recorder(JSON.stringify(obj)); }
    catch (e) { /* binding may not be ready yet — drop silently */ }
  };

  // Best-effort selector for a target element. Walks up looking for
  // attributes that survive TV's class-name churn (data-name, aria-label,
  // role, name). Falls back to the deepest stable class token. Never
  // returns autogenerated CSS-module hashes (those start with a lowercase
  // letter and contain a dash + 5+ random chars).
  const _bestSelector = (el) => {
    if (!el || el.nodeType !== 1) return null;
    let cur = el, depth = 0;
    while (cur && depth < 6) {
      if (cur.dataset && cur.dataset.name) return `[data-name="${cur.dataset.name}"]`;
      const aria = cur.getAttribute && cur.getAttribute('aria-label');
      if (aria) return `[aria-label="${aria.replace(/"/g, '\\"')}"]`;
      const role = cur.getAttribute && cur.getAttribute('role');
      if (role && cur.id) return `${cur.tagName.toLowerCase()}#${cur.id}[role="${role}"]`;
      if (cur.id && !/^[a-z0-9]+-[a-z0-9]{5,}$/i.test(cur.id)) return `#${cur.id}`;
      cur = cur.parentElement; depth++;
    }
    return el.tagName ? el.tagName.toLowerCase() : null;
  };

  const _targetKind = (el) => {
    if (!el || !el.tagName) return 'unknown';
    const tag = el.tagName.toLowerCase();
    if (tag === 'canvas') return 'canvas';
    if (tag === 'input' || tag === 'textarea') return 'input';
    if (el.isContentEditable) return 'input';
    return 'element';
  };

  // KEYDOWN — capture every key on the document (capture phase) so we
  // see Shift+Right etc. before TV swallows them. For typing inside an
  // input we still record the key (so we can see Cmd+K, Tab, etc.) but
  // tag target_kind so the consumer can filter.
  document.addEventListener('keydown', (ev) => {
    send({
      kind: 'key',
      key: ev.key,
      code: ev.code,
      mods: { shift: ev.shiftKey, ctrl: ev.ctrlKey, alt: ev.altKey, meta: ev.metaKey },
      target_kind: _targetKind(ev.target),
      target_selector: _bestSelector(ev.target),
      ts: Date.now(),
    });
  }, true);

  // MOUSEDOWN — using mousedown over click catches drag-starts (e.g.
  // dragging a level on TV) which are key to learning chart manipulation.
  document.addEventListener('mousedown', (ev) => {
    const t = ev.target;
    const kind = _targetKind(t);
    let text = null;
    if (kind === 'element' && t.innerText) text = t.innerText.trim().slice(0, 80);
    send({
      kind: 'click',
      button: ev.button,
      x: Math.round(ev.clientX),
      y: Math.round(ev.clientY),
      target_kind: kind,
      target_selector: _bestSelector(t),
      target_text: text,
      ts: Date.now(),
    });
  }, true);

  // DBLCLICK — TV uses double-click on prices / drawings constantly.
  document.addEventListener('dblclick', (ev) => {
    send({
      kind: 'dblclick',
      x: Math.round(ev.clientX), y: Math.round(ev.clientY),
      target_kind: _targetKind(ev.target),
      target_selector: _bestSelector(ev.target),
      ts: Date.now(),
    });
  }, true);

  // FOCUS on inputs — tells us when the user opened search, switched
  // to a text field, etc. Without this, key events look identical
  // whether the user is typing into the symbol box or the chart.
  document.addEventListener('focusin', (ev) => {
    if (_targetKind(ev.target) !== 'input') return;
    send({
      kind: 'focus_input',
      target_selector: _bestSelector(ev.target),
      placeholder: ev.target.placeholder || null,
      ts: Date.now(),
    });
  }, true);

  // Heartbeat — fires once when the recorder finishes installing on a
  // given document. Lets the consumer confirm injection worked even if
  // the user hasn't done anything yet.
  send({ kind: 'recorder_installed', url: location.href, ts: Date.now() });
})();
"""


_state: dict[str, Any] = {
    "active": False,
    "path": None,
    "started_at": None,
    "pw": None,           # async_playwright() context, kept open
    "browser": None,      # CDP-connected browser
    "pages_attached": [], # pages we've installed the binding on
    "events": 0,
    "notes": 0,
    "writer_lock": None,
    "fh": None,
}


def _now_iso() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%S%z")


async def _on_event_from_page(_source: Any, payload: str) -> None:
    """Binding callback — page.expose_binding hands us (source, *args).
    Source is a frame reference we don't need; payload is the JSON
    string the JS sent."""
    try:
        ev = json.loads(payload)
    except Exception:
        return
    ev["ts_iso"] = _now_iso()
    await _write(ev)
    _state["events"] += 1


async def _write(entry: dict) -> None:
    """Serialize one event to the JSONL file. Lock so concurrent
    bindings + notes don't interleave bytes."""
    fh = _state.get("fh")
    if fh is None:
        return
    lock = _state["writer_lock"]
    async with lock:
        fh.write(json.dumps(entry) + "\n")
        fh.flush()


async def _attach_page(page: Page) -> None:
    """Install the binding + recorder on one TV page. Idempotent —
    expose_binding raises if the binding already exists, so we catch
    and re-inject only the script."""
    try:
        await page.expose_binding("__1run_recorder", _on_event_from_page)
    except Exception:
        # Already bound on a previous attach. The init-script + the
        # __1run_recorder_installed guard make re-injection a no-op,
        # so just ensure the script is in place for the current frame.
        pass
    # add_init_script ensures the recorder re-installs after every
    # navigation (chart reloads, replay-jumps, etc.)
    await page.add_init_script(_RECORDER_JS)
    # And run it now for the current document.
    await page.evaluate(_RECORDER_JS)

    page.on("framenavigated", lambda fr: asyncio.create_task(
        _write({
            "kind": "navigate",
            "url": fr.url,
            "is_main": fr is page.main_frame,
            "ts_iso": _now_iso(),
        })
    ))

    if page not in _state["pages_attached"]:
        _state["pages_attached"].append(page)


async def start_recording(cdp_url: str) -> dict:
    """Begin a recording. Connects to the user's Chrome over CDP,
    finds every TradingView tab, and instruments them. Re-attaching
    after start (e.g. user opens a new chart tab) is not handled in
    this first cut — caller should open the chart they want to record
    BEFORE pressing Record.
    """
    if _state["active"]:
        return {"ok": False, "error": "recording already active",
                "path": str(_state["path"])}

    rec_dir = Path(__file__).resolve().parent.parent / "recordings"
    rec_dir.mkdir(parents=True, exist_ok=True)
    stamp = time.strftime("%Y-%m-%d_%H%M%S")
    path = rec_dir / f"replay_{stamp}.jsonl"

    pw = await async_playwright().start()
    try:
        browser = await pw.chromium.connect_over_cdp(cdp_url)
    except Exception as e:
        await pw.stop()
        raise RuntimeError(
            f"failed to connect to Chrome at {cdp_url}: {e}. "
            "Is start_chrome_cdp.sh running?"
        )

    if not browser.contexts:
        await browser.close()
        await pw.stop()
        raise RuntimeError(f"connected to {cdp_url} but no contexts found")

    ctx = browser.contexts[0]
    # Match the chart specifically, not /accounts/signin or other TV pages
    # — otherwise the recorder attaches to the wrong tab and quietly
    # captures nothing. /chart/ also covers replay (same URL family).
    tv_pages = [p for p in ctx.pages if "tradingview.com/chart" in (p.url or "")]
    if not tv_pages:
        all_tv = [p.url for p in ctx.pages if "tradingview.com" in (p.url or "")]
        await browser.close()
        await pw.stop()
        raise RuntimeError(
            "no TradingView /chart/ tab found — open a chart first, "
            f"then press Record. Currently open TV tabs: {all_tv or 'none'}"
        )

    fh = path.open("a")
    _state.update({
        "active": True,
        "path": path,
        "started_at": _now_iso(),
        "pw": pw,
        "browser": browser,
        "pages_attached": [],
        "events": 0,
        "notes": 0,
        "writer_lock": asyncio.Lock(),
        "fh": fh,
    })

    await _write({
        "kind": "session_start",
        "ts_iso": _now_iso(),
        "n_tv_pages": len(tv_pages),
        "urls": [p.url for p in tv_pages],
    })

    for page in tv_pages:
        try:
            await _attach_page(page)
        except Exception as e:
            await _write({
                "kind": "attach_fail",
                "url": getattr(page, "url", "?"),
                "error": f"{type(e).__name__}: {e}",
                "ts_iso": _now_iso(),
            })

    # Attach to any TV chart tab opened *after* recording starts — saves
    # the user from having to restart if they pop a new chart mid-session.
    def _on_new_page(page: Page) -> None:
        async def _maybe_attach():
            try:
                await page.wait_for_load_state("domcontentloaded", timeout=15_000)
            except Exception:
                pass
            if "tradingview.com/chart" in (page.url or ""):
                try:
                    await _attach_page(page)
                    await _write({
                        "kind": "attach_new_page",
                        "url": page.url, "ts_iso": _now_iso(),
                    })
                except Exception as e:
                    await _write({
                        "kind": "attach_fail",
                        "url": page.url,
                        "error": f"{type(e).__name__}: {e}",
                        "ts_iso": _now_iso(),
                    })
        asyncio.create_task(_maybe_attach())
    ctx.on("page", _on_new_page)

    audit.log("recording.start", path=str(path), n_pages=len(tv_pages))
    return {
        "ok": True, "path": str(path),
        "started_at": _state["started_at"],
        "n_pages": len(tv_pages),
    }


async def add_note(text: str) -> dict:
    """Append an intent note to the active recording. No-op (returns
    error) if no recording is active."""
    if not _state["active"]:
        return {"ok": False, "error": "no active recording"}
    text = (text or "").strip()
    if not text:
        return {"ok": False, "error": "empty note"}
    await _write({
        "kind": "note",
        "text": text[:2000],
        "ts_iso": _now_iso(),
    })
    _state["notes"] += 1
    audit.log("recording.note", text=text[:120])
    return {"ok": True, "notes": _state["notes"]}


async def stop_recording() -> dict:
    """Close the JSONL file and disconnect from Chrome (without
    closing the user's browser)."""
    if not _state["active"]:
        return {"ok": False, "error": "no active recording"}

    await _write({
        "kind": "session_end",
        "ts_iso": _now_iso(),
        "events": _state["events"],
        "notes": _state["notes"],
    })

    path = _state["path"]
    started_at = _state["started_at"]
    events = _state["events"]
    notes = _state["notes"]

    try:
        _state["fh"].close()
    except Exception:
        pass

    # Disconnect from Chrome — same pattern as session.tv_context's
    # finally block: close the CDP transport, never close the context
    # (that would close the user's browser).
    try:
        await _state["browser"].close()
    except Exception:
        pass
    try:
        await _state["pw"].stop()
    except Exception:
        pass

    _state.update({
        "active": False, "path": None, "started_at": None,
        "pw": None, "browser": None, "pages_attached": [],
        "events": 0, "notes": 0, "writer_lock": None, "fh": None,
    })

    audit.log("recording.stop", path=str(path),
              events=events, notes=notes)
    return {
        "ok": True, "path": str(path),
        "started_at": started_at, "stopped_at": _now_iso(),
        "events": events, "notes": notes,
    }


def status() -> dict:
    """Cheap probe — used by the UI to show the Record button state."""
    if not _state["active"]:
        return {"active": False}
    return {
        "active": True,
        "path": str(_state["path"]),
        "started_at": _state["started_at"],
        "events": _state["events"],
        "notes": _state["notes"],
    }
